spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitple_project
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret: b1ee7f2bb90b78b2274f86936a50c6619fdd96ab9ca837f7902b3f53cc8992ff4b45a58b91cfd1103f85281ea694151d7e83ea0e36d91e022d124223317caf07
server:
  port: 8080

cors:
  allowed-origins: http://localhost:7070
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

toss:
  payments:
    secret-key: ${test_sk_GjLJoQ1aVZ9KQRgbxBkJ3w6KYe2R}

kakao:
  pay:
    client-id: A7EAB5C0E188BA0EF82B  # 클라이언트 ID
    client-secret: 749696A87ABCFA738A36  # 클라이언트 시크릿
    secret-key: PRD441A04CE52647D4E94FFA919FD67242007B40  # 시크릿 키