spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1089148676962-ahf2kg6quom7819mpcumeoqrkfgba4ml.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:7070/
            scope:
              - email
              - profile
          naver:
            client-id: bHW4MOoFuPAms8uq8H6B
            client-secret: V71_DE71p_
            client-name: GymSparta
            redirect-uri: http://localhost:7070/
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 968f4f8b59adedc72ab3202c99d837d1
            client-secret: 3RbUuN46iZZ5MIrkma1RZ1vXfHnrfXFP
            redirect-uri: http://localhost:7070/
            authorization-grant-type: authorization_code
            client-name: Fitple
            client-authentication-method: POST
            scope:
              - account_email
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    url: jdbc:mysql://localhost:3306/fitple_project
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret: b1ee7f2bb90b78b2274f86936a50c6619fdd96ab9ca837f7902b3f53cc8992ff4b45a58b91cfd1103f85281ea694151d7e83ea0e36d91e022d124223317caf07
server:
  port: 8080

#logging:
#  level:
#    root: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.springframework.security: DEBUG
#    reactor:
#      netty: DEBUG